org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
java_toolchain_version=21

mod_id=chopdownupdated
mod_name=Chop Down Updated
mod_license=LGPL-2.1
mod_version=1.3.0
mod_authors=Shovinus,Ternsip
mod_description=Allows cutting down an entire tree in one go.
group_name=com.shovinus

minecraft_version=1.21.1
minecraft_version_range=[1.21,1.21.2)
forge_version=52.1.14
forge_version_range=[52,53)
loader_version_range=[52,53)
