org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_id=chopdownupdated
mod_name=Chop Down Updated
mod_license=LGPL-2.1
mod_version=1.4.0
mod_authors=Shovinus,Ternsip
mod_description=Allows cutting down an entire tree in one go.
group_name=com.shovinus

minecraft_version=1.21.1
minecraft_version_compat=1.21-1.21.1
minecraft_version_min=1.21
minecraft_version_max=1.21.1
loader_version=0.19.3
loom_version=1.17.16
fabric_api_version=0.116.14+1.21.1
