org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_id=chopdownupdated
mod_name=Chop Down Updated
mod_license=LGPL-2.1
mod_version=1.3.0
mod_authors=Shovinus,Ternsip
mod_description=Allows cutting down an entire tree in one go.
group_name=com.shovinus

minecraft_version=1.20.1
minecraft_version_range=[1.20,1.20.7)
forge_version=47.4.20
forge_version_range=[46,51)
loader_version_range=[46,51)
